### ISSUE TITLE
Make JRuby work - basics

### ISSUE THREAD

**Issue by ELynx** [ELynx/pokemon-go-xposed-mitm#6]
Right now JRuby is added to app, but even test scripts are not working.
Need to set up JRuby to execute at least hello-world level scripts.

**Comment by griest024** [comment]
I recommend leaving all your Java the way it was and running all ruby-relevant tasks in rake. I am familiar with JRuby, but not using it in android apps. Do you have to tell gradle to include it or can you stuff jruby-complete.jar inside a folder somewhere?

**Comment by griest024** [comment]
@ELynx I think [SL4A](https://github.com/damonkohler/sl4a) is what we want to use. The tricky bit is going to be loading your java from the script, as I'm not sure how the load path will behave for scripts run from the terminal.

EDIT: On second thought it would probably be simpler to include the jruby-complete jar with the app and invoke it to run our scripts. The downside is that it is 22 MB.

**Comment by griest024** [comment]
I think you need to get your scripting container through [JRubyAdapter](https://github.com/ruboto/ruboto-irb/blob/master/src/org/ruboto/JRubyAdapter.java#L127). Here is a really useful [wiki entry](https://github.com/ruboto/ruboto/wiki/How-Ruboto-Works#jrubyadapterjava).

**Comment by ELynx** [comment]
@griest024 Thank you for help!
Right now I am trying to put different jruby-... into app to find one that will actually work. For now I am fine with package size, I hope to make it work first, make small and tidy later.
Will read into adapter.

**Comment by griest024** [comment]
@ELynx can you add me as a collaborator?

**Comment by ELynx** [comment]
@griest024 
Request sent.
I managed to add all ruboto sources and initiate JRuby loading, but it fails to start now.
Also ruboto sources will need a rework, there will be no need for splash screen and dialog to pick JRuby and core apks.

**Comment by griest024** [comment]
Yes we can definitely interrupt the start up process before the SplashScreen. When I try to run from master I get:

```
FATAL EXCEPTION: main
                                                                     Process: com.elynx.pogoxmitm, PID: 14821
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.elynx.pogoxmitm/com.elynx.pogoxmitm.ScriptTestActivity}: java.lang.RuntimeException: Either script or predefined class must be present.
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:161)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:157)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5356)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                         at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: java.lang.RuntimeException: Either script or predefined class must be present.
                                                                         at org.ruboto.ScriptLoader.loadScript(ScriptLoader.java:105)
                                                                         at org.ruboto.RubotoActivity.onCreate(RubotoActivity.java:199)
                                                                         at org.ruboto.EntryPointActivity.onCreate(EntryPointActivity.java:26)
                                                                         at com.elynx.pogoxmitm.ScriptTestActivity.onCreate(ScriptTestActivity.java:14)
                                                                         at android.app.Activity.performCreate(Activity.java:5426)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363) 
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:161) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:157) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5356) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
                                                                         at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by griest024** [comment]
@ELynx which is the original main activity? before you started testing scripts?

**Comment by griest024** [comment]
@ELynx wow I can't believe it was that easy. Note that this skips the entire Ruboto boot process (SplashScreen etc.)

**Comment by griest024** [comment]
One more note: I think it is using core jruby. It might be better to package jruby along with the app.
